### ISSUE TITLE
sorry for opening this issue

### ISSUE THREAD

**Issue by bigpo** [pau1o-hs/Graduation-stuffs#1]
Hi, I'm coming from the repo Learned-Motion-Matching, I'm wondering why you delete this repo? sorry for bothering you.

**Comment by pau1o-hs** [comment]
Hi mate! Unfortunately my professor from college said would be better to make it private, we're trying to make a paper about it, sorry :(. But as soon as I finish, it will be open again!

Out of curiosity, what was your purpose with the repo?

**Comment by bigpo** [comment]
> Hi mate! Unfortunately my professor from college said would be better to make it private, we're trying to make a paper about it, sorry :(. But as soon as I finish, it will be open again!
> 
> Out of curiosity, what was your purpose with the repo?

I'm finding a way to generate reasonable motion by some conditions like trajectory or motion category. Good Luck with your work, hope  to see it soon :).

**Comment by pau1o-hs** [comment]
Actually I'm letting it open by now, what I did was just an implemetation of an existing [paper](https://dl.acm.org/doi/abs/10.1145/3386569.3392440). And I need to show it in my resume hahaha. Maybe it's more worthwhile to create another repository when I start doing something new. Sorry for the inconvenient.
